// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/strongduanmu/netty/protobuf/Product.proto

package com.strongduanmu.netty.protobuf;

public final class Product {
  private Product() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProductBasicInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netty.protobuf.ProductBasicInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *名称
     * </pre>
     *
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <pre>
     *名称
     * </pre>
     *
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     *名称
     * </pre>
     *
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     *有效期
     * </pre>
     *
     * <code>optional int32 validate = 2;</code>
     */
    boolean hasValidate();
    /**
     * <pre>
     *有效期
     * </pre>
     *
     * <code>optional int32 validate = 2;</code>
     */
    int getValidate();

    /**
     * <pre>
     *单位
     * </pre>
     *
     * <code>optional string unit = 3;</code>
     */
    boolean hasUnit();
    /**
     * <pre>
     *单位
     * </pre>
     *
     * <code>optional string unit = 3;</code>
     */
    java.lang.String getUnit();
    /**
     * <pre>
     *单位
     * </pre>
     *
     * <code>optional string unit = 3;</code>
     */
    com.google.protobuf.ByteString
        getUnitBytes();
  }
  /**
   * Protobuf type {@code netty.protobuf.ProductBasicInfo}
   */
  public  static final class ProductBasicInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:netty.protobuf.ProductBasicInfo)
      ProductBasicInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProductBasicInfo.newBuilder() to construct.
    private ProductBasicInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProductBasicInfo() {
      name_ = "";
      unit_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ProductBasicInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProductBasicInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              validate_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              unit_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.strongduanmu.netty.protobuf.Product.internal_static_netty_protobuf_ProductBasicInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.strongduanmu.netty.protobuf.Product.internal_static_netty_protobuf_ProductBasicInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.strongduanmu.netty.protobuf.Product.ProductBasicInfo.class, com.strongduanmu.netty.protobuf.Product.ProductBasicInfo.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     *名称
     * </pre>
     *
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *名称
     * </pre>
     *
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *名称
     * </pre>
     *
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALIDATE_FIELD_NUMBER = 2;
    private int validate_;
    /**
     * <pre>
     *有效期
     * </pre>
     *
     * <code>optional int32 validate = 2;</code>
     */
    public boolean hasValidate() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *有效期
     * </pre>
     *
     * <code>optional int32 validate = 2;</code>
     */
    public int getValidate() {
      return validate_;
    }

    public static final int UNIT_FIELD_NUMBER = 3;
    private volatile java.lang.Object unit_;
    /**
     * <pre>
     *单位
     * </pre>
     *
     * <code>optional string unit = 3;</code>
     */
    public boolean hasUnit() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     *单位
     * </pre>
     *
     * <code>optional string unit = 3;</code>
     */
    public java.lang.String getUnit() {
      java.lang.Object ref = unit_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          unit_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *单位
     * </pre>
     *
     * <code>optional string unit = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUnitBytes() {
      java.lang.Object ref = unit_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, validate_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, unit_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, validate_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, unit_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.strongduanmu.netty.protobuf.Product.ProductBasicInfo)) {
        return super.equals(obj);
      }
      com.strongduanmu.netty.protobuf.Product.ProductBasicInfo other = (com.strongduanmu.netty.protobuf.Product.ProductBasicInfo) obj;

      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasValidate() != other.hasValidate()) return false;
      if (hasValidate()) {
        if (getValidate()
            != other.getValidate()) return false;
      }
      if (hasUnit() != other.hasUnit()) return false;
      if (hasUnit()) {
        if (!getUnit()
            .equals(other.getUnit())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasValidate()) {
        hash = (37 * hash) + VALIDATE_FIELD_NUMBER;
        hash = (53 * hash) + getValidate();
      }
      if (hasUnit()) {
        hash = (37 * hash) + UNIT_FIELD_NUMBER;
        hash = (53 * hash) + getUnit().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.strongduanmu.netty.protobuf.Product.ProductBasicInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.strongduanmu.netty.protobuf.Product.ProductBasicInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.strongduanmu.netty.protobuf.Product.ProductBasicInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.strongduanmu.netty.protobuf.Product.ProductBasicInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.strongduanmu.netty.protobuf.Product.ProductBasicInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.strongduanmu.netty.protobuf.Product.ProductBasicInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.strongduanmu.netty.protobuf.Product.ProductBasicInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.strongduanmu.netty.protobuf.Product.ProductBasicInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.strongduanmu.netty.protobuf.Product.ProductBasicInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.strongduanmu.netty.protobuf.Product.ProductBasicInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.strongduanmu.netty.protobuf.Product.ProductBasicInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.strongduanmu.netty.protobuf.Product.ProductBasicInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.strongduanmu.netty.protobuf.Product.ProductBasicInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netty.protobuf.ProductBasicInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netty.protobuf.ProductBasicInfo)
        com.strongduanmu.netty.protobuf.Product.ProductBasicInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.strongduanmu.netty.protobuf.Product.internal_static_netty_protobuf_ProductBasicInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.strongduanmu.netty.protobuf.Product.internal_static_netty_protobuf_ProductBasicInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.strongduanmu.netty.protobuf.Product.ProductBasicInfo.class, com.strongduanmu.netty.protobuf.Product.ProductBasicInfo.Builder.class);
      }

      // Construct using com.strongduanmu.netty.protobuf.Product.ProductBasicInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        validate_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        unit_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.strongduanmu.netty.protobuf.Product.internal_static_netty_protobuf_ProductBasicInfo_descriptor;
      }

      @java.lang.Override
      public com.strongduanmu.netty.protobuf.Product.ProductBasicInfo getDefaultInstanceForType() {
        return com.strongduanmu.netty.protobuf.Product.ProductBasicInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.strongduanmu.netty.protobuf.Product.ProductBasicInfo build() {
        com.strongduanmu.netty.protobuf.Product.ProductBasicInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.strongduanmu.netty.protobuf.Product.ProductBasicInfo buildPartial() {
        com.strongduanmu.netty.protobuf.Product.ProductBasicInfo result = new com.strongduanmu.netty.protobuf.Product.ProductBasicInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.validate_ = validate_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.unit_ = unit_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.strongduanmu.netty.protobuf.Product.ProductBasicInfo) {
          return mergeFrom((com.strongduanmu.netty.protobuf.Product.ProductBasicInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.strongduanmu.netty.protobuf.Product.ProductBasicInfo other) {
        if (other == com.strongduanmu.netty.protobuf.Product.ProductBasicInfo.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasValidate()) {
          setValidate(other.getValidate());
        }
        if (other.hasUnit()) {
          bitField0_ |= 0x00000004;
          unit_ = other.unit_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.strongduanmu.netty.protobuf.Product.ProductBasicInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.strongduanmu.netty.protobuf.Product.ProductBasicInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <pre>
       *名称
       * </pre>
       *
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *名称
       * </pre>
       *
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *名称
       * </pre>
       *
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *名称
       * </pre>
       *
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *名称
       * </pre>
       *
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *名称
       * </pre>
       *
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int validate_ ;
      /**
       * <pre>
       *有效期
       * </pre>
       *
       * <code>optional int32 validate = 2;</code>
       */
      public boolean hasValidate() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *有效期
       * </pre>
       *
       * <code>optional int32 validate = 2;</code>
       */
      public int getValidate() {
        return validate_;
      }
      /**
       * <pre>
       *有效期
       * </pre>
       *
       * <code>optional int32 validate = 2;</code>
       */
      public Builder setValidate(int value) {
        bitField0_ |= 0x00000002;
        validate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *有效期
       * </pre>
       *
       * <code>optional int32 validate = 2;</code>
       */
      public Builder clearValidate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        validate_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object unit_ = "";
      /**
       * <pre>
       *单位
       * </pre>
       *
       * <code>optional string unit = 3;</code>
       */
      public boolean hasUnit() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       *单位
       * </pre>
       *
       * <code>optional string unit = 3;</code>
       */
      public java.lang.String getUnit() {
        java.lang.Object ref = unit_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            unit_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *单位
       * </pre>
       *
       * <code>optional string unit = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUnitBytes() {
        java.lang.Object ref = unit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          unit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *单位
       * </pre>
       *
       * <code>optional string unit = 3;</code>
       */
      public Builder setUnit(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        unit_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *单位
       * </pre>
       *
       * <code>optional string unit = 3;</code>
       */
      public Builder clearUnit() {
        bitField0_ = (bitField0_ & ~0x00000004);
        unit_ = getDefaultInstance().getUnit();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *单位
       * </pre>
       *
       * <code>optional string unit = 3;</code>
       */
      public Builder setUnitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        unit_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:netty.protobuf.ProductBasicInfo)
    }

    // @@protoc_insertion_point(class_scope:netty.protobuf.ProductBasicInfo)
    private static final com.strongduanmu.netty.protobuf.Product.ProductBasicInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.strongduanmu.netty.protobuf.Product.ProductBasicInfo();
    }

    public static com.strongduanmu.netty.protobuf.Product.ProductBasicInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ProductBasicInfo>
        PARSER = new com.google.protobuf.AbstractParser<ProductBasicInfo>() {
      @java.lang.Override
      public ProductBasicInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProductBasicInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProductBasicInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProductBasicInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.strongduanmu.netty.protobuf.Product.ProductBasicInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_protobuf_ProductBasicInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_netty_protobuf_ProductBasicInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n;src/main/java/com/strongduanmu/netty/p" +
      "rotobuf/Product.proto\022\016netty.protobuf\"@\n" +
      "\020ProductBasicInfo\022\014\n\004name\030\001 \002(\t\022\020\n\010valid" +
      "ate\030\002 \001(\005\022\014\n\004unit\030\003 \001(\tB,\n\037com.strongdua" +
      "nmu.netty.protobufB\007ProductH\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_netty_protobuf_ProductBasicInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_netty_protobuf_ProductBasicInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_netty_protobuf_ProductBasicInfo_descriptor,
        new java.lang.String[] { "Name", "Validate", "Unit", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
